# Site Settings
title: Doc test
email: isabel@eyeem.com
description: >
  A dummy test for doc page.
baseurl: "/startjekyll"
url: "http://isabel-schwende.github.io"

github_username:  isabel-schwende
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
